name: LambdaQuiz CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  setup-jdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'sbt'

  tests:
    needs: [setup-jdk, quality]
    runs-on: ubuntu-la:test
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: sbt test

  quality:
    needs: setup-jdk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check code quality
        run: sbt scalafmtCheckAll
