name: LambdaQuiz CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  OS: 'ubuntu-latest'
  JAVA_VERSION: '17'
  DISTRIBUTION: 'adopt'
  CACHE: 'sbt'

jobs:
  setup-jdk:
    runs-on: ${{ env.OS }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHE }}

  quality:
    needs: setup-jdk
    runs-on: ${{ env.OS }}
    steps:
      - uses: actions/checkout@v4
      - name: Check code quality
        run: sbt scalafmtCheckAll

  tests:
    needs: [setup-jdk, quality]
    runs-on: ${{ env.OS }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: sbt test
