name: LambdaQuiz CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    needs: quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: sbt test

  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Check code quality
      run: sbt scalafmtCheckAll
