name: LambdaQuiz CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  setup:
    uses: ./.github/workflows/setup-jdk.yml
    with:
      os: ${{ matrix.os }}

  tests:
    needs: [ setup, quality ]
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: sbt test

  quality:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Check code quality
        run: sbt scalafmtCheckAll
