name: LambdaQuiz CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  quality:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'sbt'
      - name: Check code quality
        run: sbt scalafmtCheckAll

  tests:
    needs: quality
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'sbt'
      - name: Run tests
        run: sbt test
