name: LambdaQuiz CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'sbt'
      - name: Run tests
        run: sbt test

  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'sbt'
      - name: Check code quality
        run: sbt scalafmtCheckAll
